// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: biblioteca.proto

#include "biblioteca.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace biblioteca {
class PeticionIsbnDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PeticionIsbn> _instance;
} _PeticionIsbn_default_instance_;
class PeticionTituloDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PeticionTitulo> _instance;
} _PeticionTitulo_default_instance_;
class RespuestaPrestamoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RespuestaPrestamo> _instance;
} _RespuestaPrestamo_default_instance_;
class RespuestaConsultaDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RespuestaConsulta> _instance;
} _RespuestaConsulta_default_instance_;
class RespuestaDevolucionDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RespuestaDevolucion> _instance;
} _RespuestaDevolucion_default_instance_;
}  // namespace biblioteca
static void InitDefaultsscc_info_PeticionIsbn_biblioteca_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::biblioteca::_PeticionIsbn_default_instance_;
    new (ptr) ::biblioteca::PeticionIsbn();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::biblioteca::PeticionIsbn::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PeticionIsbn_biblioteca_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_PeticionIsbn_biblioteca_2eproto}, {}};

static void InitDefaultsscc_info_PeticionTitulo_biblioteca_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::biblioteca::_PeticionTitulo_default_instance_;
    new (ptr) ::biblioteca::PeticionTitulo();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::biblioteca::PeticionTitulo::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PeticionTitulo_biblioteca_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_PeticionTitulo_biblioteca_2eproto}, {}};

static void InitDefaultsscc_info_RespuestaConsulta_biblioteca_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::biblioteca::_RespuestaConsulta_default_instance_;
    new (ptr) ::biblioteca::RespuestaConsulta();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::biblioteca::RespuestaConsulta::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RespuestaConsulta_biblioteca_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_RespuestaConsulta_biblioteca_2eproto}, {}};

static void InitDefaultsscc_info_RespuestaDevolucion_biblioteca_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::biblioteca::_RespuestaDevolucion_default_instance_;
    new (ptr) ::biblioteca::RespuestaDevolucion();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::biblioteca::RespuestaDevolucion::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RespuestaDevolucion_biblioteca_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_RespuestaDevolucion_biblioteca_2eproto}, {}};

static void InitDefaultsscc_info_RespuestaPrestamo_biblioteca_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::biblioteca::_RespuestaPrestamo_default_instance_;
    new (ptr) ::biblioteca::RespuestaPrestamo();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::biblioteca::RespuestaPrestamo::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RespuestaPrestamo_biblioteca_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_RespuestaPrestamo_biblioteca_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_biblioteca_2eproto[5];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_biblioteca_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_biblioteca_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_biblioteca_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::biblioteca::PeticionIsbn, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::biblioteca::PeticionIsbn, isbn_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::biblioteca::PeticionTitulo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::biblioteca::PeticionTitulo, titulo_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::biblioteca::RespuestaPrestamo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::biblioteca::RespuestaPrestamo, aprobado_),
  PROTOBUF_FIELD_OFFSET(::biblioteca::RespuestaPrestamo, fecha_devolucion_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::biblioteca::RespuestaConsulta, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::biblioteca::RespuestaConsulta, existe_),
  PROTOBUF_FIELD_OFFSET(::biblioteca::RespuestaConsulta, disponibles_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::biblioteca::RespuestaDevolucion, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::biblioteca::RespuestaDevolucion, exito_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::biblioteca::PeticionIsbn)},
  { 6, -1, sizeof(::biblioteca::PeticionTitulo)},
  { 12, -1, sizeof(::biblioteca::RespuestaPrestamo)},
  { 19, -1, sizeof(::biblioteca::RespuestaConsulta)},
  { 26, -1, sizeof(::biblioteca::RespuestaDevolucion)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::biblioteca::_PeticionIsbn_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::biblioteca::_PeticionTitulo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::biblioteca::_RespuestaPrestamo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::biblioteca::_RespuestaConsulta_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::biblioteca::_RespuestaDevolucion_default_instance_),
};

const char descriptor_table_protodef_biblioteca_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020biblioteca.proto\022\nbiblioteca\"\034\n\014Petici"
  "onIsbn\022\014\n\004isbn\030\001 \001(\t\" \n\016PeticionTitulo\022\016"
  "\n\006titulo\030\001 \001(\t\"\?\n\021RespuestaPrestamo\022\020\n\010a"
  "probado\030\001 \001(\010\022\030\n\020fecha_devolucion\030\002 \001(\t\""
  "8\n\021RespuestaConsulta\022\016\n\006existe\030\001 \001(\010\022\023\n\013"
  "disponibles\030\002 \001(\005\"$\n\023RespuestaDevolucion"
  "\022\r\n\005exito\030\001 \001(\0102\275\002\n\021GestionBiblioteca\022J\n"
  "\017PrestamoPorIsbn\022\030.biblioteca.PeticionIs"
  "bn\032\035.biblioteca.RespuestaPrestamo\022N\n\021Pre"
  "stamoPorTitulo\022\032.biblioteca.PeticionTitu"
  "lo\032\035.biblioteca.RespuestaPrestamo\022C\n\010Con"
  "sulta\022\030.biblioteca.PeticionIsbn\032\035.biblio"
  "teca.RespuestaConsulta\022G\n\nDevolucion\022\030.b"
  "iblioteca.PeticionIsbn\032\037.biblioteca.Resp"
  "uestaDevolucionb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_biblioteca_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_biblioteca_2eproto_sccs[5] = {
  &scc_info_PeticionIsbn_biblioteca_2eproto.base,
  &scc_info_PeticionTitulo_biblioteca_2eproto.base,
  &scc_info_RespuestaConsulta_biblioteca_2eproto.base,
  &scc_info_RespuestaDevolucion_biblioteca_2eproto.base,
  &scc_info_RespuestaPrestamo_biblioteca_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_biblioteca_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_biblioteca_2eproto = {
  false, false, descriptor_table_protodef_biblioteca_2eproto, "biblioteca.proto", 583,
  &descriptor_table_biblioteca_2eproto_once, descriptor_table_biblioteca_2eproto_sccs, descriptor_table_biblioteca_2eproto_deps, 5, 0,
  schemas, file_default_instances, TableStruct_biblioteca_2eproto::offsets,
  file_level_metadata_biblioteca_2eproto, 5, file_level_enum_descriptors_biblioteca_2eproto, file_level_service_descriptors_biblioteca_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_biblioteca_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_biblioteca_2eproto)), true);
namespace biblioteca {

// ===================================================================

void PeticionIsbn::InitAsDefaultInstance() {
}
class PeticionIsbn::_Internal {
 public:
};

PeticionIsbn::PeticionIsbn(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:biblioteca.PeticionIsbn)
}
PeticionIsbn::PeticionIsbn(const PeticionIsbn& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  isbn_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_isbn().empty()) {
    isbn_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_isbn(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:biblioteca.PeticionIsbn)
}

void PeticionIsbn::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PeticionIsbn_biblioteca_2eproto.base);
  isbn_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

PeticionIsbn::~PeticionIsbn() {
  // @@protoc_insertion_point(destructor:biblioteca.PeticionIsbn)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PeticionIsbn::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  isbn_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void PeticionIsbn::ArenaDtor(void* object) {
  PeticionIsbn* _this = reinterpret_cast< PeticionIsbn* >(object);
  (void)_this;
}
void PeticionIsbn::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PeticionIsbn::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PeticionIsbn& PeticionIsbn::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PeticionIsbn_biblioteca_2eproto.base);
  return *internal_default_instance();
}


void PeticionIsbn::Clear() {
// @@protoc_insertion_point(message_clear_start:biblioteca.PeticionIsbn)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  isbn_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PeticionIsbn::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string isbn = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_isbn();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "biblioteca.PeticionIsbn.isbn"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PeticionIsbn::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:biblioteca.PeticionIsbn)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string isbn = 1;
  if (this->isbn().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_isbn().data(), static_cast<int>(this->_internal_isbn().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "biblioteca.PeticionIsbn.isbn");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_isbn(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:biblioteca.PeticionIsbn)
  return target;
}

size_t PeticionIsbn::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:biblioteca.PeticionIsbn)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string isbn = 1;
  if (this->isbn().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_isbn());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PeticionIsbn::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:biblioteca.PeticionIsbn)
  GOOGLE_DCHECK_NE(&from, this);
  const PeticionIsbn* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PeticionIsbn>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:biblioteca.PeticionIsbn)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:biblioteca.PeticionIsbn)
    MergeFrom(*source);
  }
}

void PeticionIsbn::MergeFrom(const PeticionIsbn& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:biblioteca.PeticionIsbn)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.isbn().size() > 0) {
    _internal_set_isbn(from._internal_isbn());
  }
}

void PeticionIsbn::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:biblioteca.PeticionIsbn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PeticionIsbn::CopyFrom(const PeticionIsbn& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:biblioteca.PeticionIsbn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PeticionIsbn::IsInitialized() const {
  return true;
}

void PeticionIsbn::InternalSwap(PeticionIsbn* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  isbn_.Swap(&other->isbn_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata PeticionIsbn::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void PeticionTitulo::InitAsDefaultInstance() {
}
class PeticionTitulo::_Internal {
 public:
};

PeticionTitulo::PeticionTitulo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:biblioteca.PeticionTitulo)
}
PeticionTitulo::PeticionTitulo(const PeticionTitulo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  titulo_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_titulo().empty()) {
    titulo_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_titulo(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:biblioteca.PeticionTitulo)
}

void PeticionTitulo::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PeticionTitulo_biblioteca_2eproto.base);
  titulo_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

PeticionTitulo::~PeticionTitulo() {
  // @@protoc_insertion_point(destructor:biblioteca.PeticionTitulo)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PeticionTitulo::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  titulo_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void PeticionTitulo::ArenaDtor(void* object) {
  PeticionTitulo* _this = reinterpret_cast< PeticionTitulo* >(object);
  (void)_this;
}
void PeticionTitulo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PeticionTitulo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PeticionTitulo& PeticionTitulo::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PeticionTitulo_biblioteca_2eproto.base);
  return *internal_default_instance();
}


void PeticionTitulo::Clear() {
// @@protoc_insertion_point(message_clear_start:biblioteca.PeticionTitulo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  titulo_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PeticionTitulo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string titulo = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_titulo();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "biblioteca.PeticionTitulo.titulo"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PeticionTitulo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:biblioteca.PeticionTitulo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string titulo = 1;
  if (this->titulo().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_titulo().data(), static_cast<int>(this->_internal_titulo().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "biblioteca.PeticionTitulo.titulo");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_titulo(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:biblioteca.PeticionTitulo)
  return target;
}

size_t PeticionTitulo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:biblioteca.PeticionTitulo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string titulo = 1;
  if (this->titulo().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_titulo());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PeticionTitulo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:biblioteca.PeticionTitulo)
  GOOGLE_DCHECK_NE(&from, this);
  const PeticionTitulo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PeticionTitulo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:biblioteca.PeticionTitulo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:biblioteca.PeticionTitulo)
    MergeFrom(*source);
  }
}

void PeticionTitulo::MergeFrom(const PeticionTitulo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:biblioteca.PeticionTitulo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.titulo().size() > 0) {
    _internal_set_titulo(from._internal_titulo());
  }
}

void PeticionTitulo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:biblioteca.PeticionTitulo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PeticionTitulo::CopyFrom(const PeticionTitulo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:biblioteca.PeticionTitulo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PeticionTitulo::IsInitialized() const {
  return true;
}

void PeticionTitulo::InternalSwap(PeticionTitulo* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  titulo_.Swap(&other->titulo_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata PeticionTitulo::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void RespuestaPrestamo::InitAsDefaultInstance() {
}
class RespuestaPrestamo::_Internal {
 public:
};

RespuestaPrestamo::RespuestaPrestamo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:biblioteca.RespuestaPrestamo)
}
RespuestaPrestamo::RespuestaPrestamo(const RespuestaPrestamo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  fecha_devolucion_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_fecha_devolucion().empty()) {
    fecha_devolucion_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_fecha_devolucion(),
      GetArena());
  }
  aprobado_ = from.aprobado_;
  // @@protoc_insertion_point(copy_constructor:biblioteca.RespuestaPrestamo)
}

void RespuestaPrestamo::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_RespuestaPrestamo_biblioteca_2eproto.base);
  fecha_devolucion_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  aprobado_ = false;
}

RespuestaPrestamo::~RespuestaPrestamo() {
  // @@protoc_insertion_point(destructor:biblioteca.RespuestaPrestamo)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RespuestaPrestamo::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  fecha_devolucion_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void RespuestaPrestamo::ArenaDtor(void* object) {
  RespuestaPrestamo* _this = reinterpret_cast< RespuestaPrestamo* >(object);
  (void)_this;
}
void RespuestaPrestamo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RespuestaPrestamo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RespuestaPrestamo& RespuestaPrestamo::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RespuestaPrestamo_biblioteca_2eproto.base);
  return *internal_default_instance();
}


void RespuestaPrestamo::Clear() {
// @@protoc_insertion_point(message_clear_start:biblioteca.RespuestaPrestamo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  fecha_devolucion_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  aprobado_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RespuestaPrestamo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool aprobado = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          aprobado_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string fecha_devolucion = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_fecha_devolucion();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "biblioteca.RespuestaPrestamo.fecha_devolucion"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RespuestaPrestamo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:biblioteca.RespuestaPrestamo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool aprobado = 1;
  if (this->aprobado() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_aprobado(), target);
  }

  // string fecha_devolucion = 2;
  if (this->fecha_devolucion().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_fecha_devolucion().data(), static_cast<int>(this->_internal_fecha_devolucion().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "biblioteca.RespuestaPrestamo.fecha_devolucion");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_fecha_devolucion(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:biblioteca.RespuestaPrestamo)
  return target;
}

size_t RespuestaPrestamo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:biblioteca.RespuestaPrestamo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string fecha_devolucion = 2;
  if (this->fecha_devolucion().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_fecha_devolucion());
  }

  // bool aprobado = 1;
  if (this->aprobado() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RespuestaPrestamo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:biblioteca.RespuestaPrestamo)
  GOOGLE_DCHECK_NE(&from, this);
  const RespuestaPrestamo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RespuestaPrestamo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:biblioteca.RespuestaPrestamo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:biblioteca.RespuestaPrestamo)
    MergeFrom(*source);
  }
}

void RespuestaPrestamo::MergeFrom(const RespuestaPrestamo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:biblioteca.RespuestaPrestamo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.fecha_devolucion().size() > 0) {
    _internal_set_fecha_devolucion(from._internal_fecha_devolucion());
  }
  if (from.aprobado() != 0) {
    _internal_set_aprobado(from._internal_aprobado());
  }
}

void RespuestaPrestamo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:biblioteca.RespuestaPrestamo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RespuestaPrestamo::CopyFrom(const RespuestaPrestamo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:biblioteca.RespuestaPrestamo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RespuestaPrestamo::IsInitialized() const {
  return true;
}

void RespuestaPrestamo::InternalSwap(RespuestaPrestamo* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  fecha_devolucion_.Swap(&other->fecha_devolucion_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(aprobado_, other->aprobado_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RespuestaPrestamo::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void RespuestaConsulta::InitAsDefaultInstance() {
}
class RespuestaConsulta::_Internal {
 public:
};

RespuestaConsulta::RespuestaConsulta(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:biblioteca.RespuestaConsulta)
}
RespuestaConsulta::RespuestaConsulta(const RespuestaConsulta& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&existe_, &from.existe_,
    static_cast<size_t>(reinterpret_cast<char*>(&disponibles_) -
    reinterpret_cast<char*>(&existe_)) + sizeof(disponibles_));
  // @@protoc_insertion_point(copy_constructor:biblioteca.RespuestaConsulta)
}

void RespuestaConsulta::SharedCtor() {
  ::memset(&existe_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&disponibles_) -
      reinterpret_cast<char*>(&existe_)) + sizeof(disponibles_));
}

RespuestaConsulta::~RespuestaConsulta() {
  // @@protoc_insertion_point(destructor:biblioteca.RespuestaConsulta)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RespuestaConsulta::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void RespuestaConsulta::ArenaDtor(void* object) {
  RespuestaConsulta* _this = reinterpret_cast< RespuestaConsulta* >(object);
  (void)_this;
}
void RespuestaConsulta::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RespuestaConsulta::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RespuestaConsulta& RespuestaConsulta::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RespuestaConsulta_biblioteca_2eproto.base);
  return *internal_default_instance();
}


void RespuestaConsulta::Clear() {
// @@protoc_insertion_point(message_clear_start:biblioteca.RespuestaConsulta)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&existe_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&disponibles_) -
      reinterpret_cast<char*>(&existe_)) + sizeof(disponibles_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RespuestaConsulta::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool existe = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          existe_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 disponibles = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          disponibles_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RespuestaConsulta::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:biblioteca.RespuestaConsulta)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool existe = 1;
  if (this->existe() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_existe(), target);
  }

  // int32 disponibles = 2;
  if (this->disponibles() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_disponibles(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:biblioteca.RespuestaConsulta)
  return target;
}

size_t RespuestaConsulta::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:biblioteca.RespuestaConsulta)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool existe = 1;
  if (this->existe() != 0) {
    total_size += 1 + 1;
  }

  // int32 disponibles = 2;
  if (this->disponibles() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_disponibles());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RespuestaConsulta::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:biblioteca.RespuestaConsulta)
  GOOGLE_DCHECK_NE(&from, this);
  const RespuestaConsulta* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RespuestaConsulta>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:biblioteca.RespuestaConsulta)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:biblioteca.RespuestaConsulta)
    MergeFrom(*source);
  }
}

void RespuestaConsulta::MergeFrom(const RespuestaConsulta& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:biblioteca.RespuestaConsulta)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.existe() != 0) {
    _internal_set_existe(from._internal_existe());
  }
  if (from.disponibles() != 0) {
    _internal_set_disponibles(from._internal_disponibles());
  }
}

void RespuestaConsulta::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:biblioteca.RespuestaConsulta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RespuestaConsulta::CopyFrom(const RespuestaConsulta& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:biblioteca.RespuestaConsulta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RespuestaConsulta::IsInitialized() const {
  return true;
}

void RespuestaConsulta::InternalSwap(RespuestaConsulta* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RespuestaConsulta, disponibles_)
      + sizeof(RespuestaConsulta::disponibles_)
      - PROTOBUF_FIELD_OFFSET(RespuestaConsulta, existe_)>(
          reinterpret_cast<char*>(&existe_),
          reinterpret_cast<char*>(&other->existe_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RespuestaConsulta::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void RespuestaDevolucion::InitAsDefaultInstance() {
}
class RespuestaDevolucion::_Internal {
 public:
};

RespuestaDevolucion::RespuestaDevolucion(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:biblioteca.RespuestaDevolucion)
}
RespuestaDevolucion::RespuestaDevolucion(const RespuestaDevolucion& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  exito_ = from.exito_;
  // @@protoc_insertion_point(copy_constructor:biblioteca.RespuestaDevolucion)
}

void RespuestaDevolucion::SharedCtor() {
  exito_ = false;
}

RespuestaDevolucion::~RespuestaDevolucion() {
  // @@protoc_insertion_point(destructor:biblioteca.RespuestaDevolucion)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RespuestaDevolucion::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void RespuestaDevolucion::ArenaDtor(void* object) {
  RespuestaDevolucion* _this = reinterpret_cast< RespuestaDevolucion* >(object);
  (void)_this;
}
void RespuestaDevolucion::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RespuestaDevolucion::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RespuestaDevolucion& RespuestaDevolucion::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RespuestaDevolucion_biblioteca_2eproto.base);
  return *internal_default_instance();
}


void RespuestaDevolucion::Clear() {
// @@protoc_insertion_point(message_clear_start:biblioteca.RespuestaDevolucion)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  exito_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RespuestaDevolucion::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool exito = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          exito_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RespuestaDevolucion::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:biblioteca.RespuestaDevolucion)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool exito = 1;
  if (this->exito() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_exito(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:biblioteca.RespuestaDevolucion)
  return target;
}

size_t RespuestaDevolucion::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:biblioteca.RespuestaDevolucion)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool exito = 1;
  if (this->exito() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RespuestaDevolucion::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:biblioteca.RespuestaDevolucion)
  GOOGLE_DCHECK_NE(&from, this);
  const RespuestaDevolucion* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RespuestaDevolucion>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:biblioteca.RespuestaDevolucion)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:biblioteca.RespuestaDevolucion)
    MergeFrom(*source);
  }
}

void RespuestaDevolucion::MergeFrom(const RespuestaDevolucion& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:biblioteca.RespuestaDevolucion)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.exito() != 0) {
    _internal_set_exito(from._internal_exito());
  }
}

void RespuestaDevolucion::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:biblioteca.RespuestaDevolucion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RespuestaDevolucion::CopyFrom(const RespuestaDevolucion& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:biblioteca.RespuestaDevolucion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RespuestaDevolucion::IsInitialized() const {
  return true;
}

void RespuestaDevolucion::InternalSwap(RespuestaDevolucion* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(exito_, other->exito_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RespuestaDevolucion::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace biblioteca
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::biblioteca::PeticionIsbn* Arena::CreateMaybeMessage< ::biblioteca::PeticionIsbn >(Arena* arena) {
  return Arena::CreateMessageInternal< ::biblioteca::PeticionIsbn >(arena);
}
template<> PROTOBUF_NOINLINE ::biblioteca::PeticionTitulo* Arena::CreateMaybeMessage< ::biblioteca::PeticionTitulo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::biblioteca::PeticionTitulo >(arena);
}
template<> PROTOBUF_NOINLINE ::biblioteca::RespuestaPrestamo* Arena::CreateMaybeMessage< ::biblioteca::RespuestaPrestamo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::biblioteca::RespuestaPrestamo >(arena);
}
template<> PROTOBUF_NOINLINE ::biblioteca::RespuestaConsulta* Arena::CreateMaybeMessage< ::biblioteca::RespuestaConsulta >(Arena* arena) {
  return Arena::CreateMessageInternal< ::biblioteca::RespuestaConsulta >(arena);
}
template<> PROTOBUF_NOINLINE ::biblioteca::RespuestaDevolucion* Arena::CreateMaybeMessage< ::biblioteca::RespuestaDevolucion >(Arena* arena) {
  return Arena::CreateMessageInternal< ::biblioteca::RespuestaDevolucion >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
