// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: biblioteca.proto
// Original file comments:
// vercion mas moderna de gRPC
#ifndef GRPC_biblioteca_2eproto__INCLUDED
#define GRPC_biblioteca_2eproto__INCLUDED

#include "biblioteca.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace biblioteca {

// ------------------------------------------------------------------------
// eL SERVIVIO: Aqui definims los 4 metodos remotos
// -------------------------------------------------------------------------
//
class GestionBiblioteca final {
 public:
  static constexpr char const* service_full_name() {
    return "biblioteca.GestionBiblioteca";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Dado el isbn, retorna respuesta al prestamo y fecha de devolucion
    virtual ::grpc::Status PrestamoPorIsbn(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::biblioteca::RespuestaPrestamo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaPrestamo>> AsyncPrestamoPorIsbn(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaPrestamo>>(AsyncPrestamoPorIsbnRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaPrestamo>> PrepareAsyncPrestamoPorIsbn(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaPrestamo>>(PrepareAsyncPrestamoPorIsbnRaw(context, request, cq));
    }
    // Dado el titulo, retorna respuesta al prestamo y fecha de devolucion
    virtual ::grpc::Status PrestamoPorTitulo(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo& request, ::biblioteca::RespuestaPrestamo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaPrestamo>> AsyncPrestamoPorTitulo(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaPrestamo>>(AsyncPrestamoPorTituloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaPrestamo>> PrepareAsyncPrestamoPorTitulo(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaPrestamo>>(PrepareAsyncPrestamoPorTituloRaw(context, request, cq));
    }
    // Dado el ISBN o codigo, retorna si se encuentra y cuantos disponibles hay
    virtual ::grpc::Status Consulta(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::biblioteca::RespuestaConsulta* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaConsulta>> AsyncConsulta(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaConsulta>>(AsyncConsultaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaConsulta>> PrepareAsyncConsulta(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaConsulta>>(PrepareAsyncConsultaRaw(context, request, cq));
    }
    // Dado el isbn, registra la devolucion
    virtual ::grpc::Status Devolucion(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::biblioteca::RespuestaDevolucion* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaDevolucion>> AsyncDevolucion(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaDevolucion>>(AsyncDevolucionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaDevolucion>> PrepareAsyncDevolucion(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaDevolucion>>(PrepareAsyncDevolucionRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Dado el isbn, retorna respuesta al prestamo y fecha de devolucion
      virtual void PrestamoPorIsbn(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaPrestamo* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PrestamoPorIsbn(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaPrestamo* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void PrestamoPorIsbn(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaPrestamo* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void PrestamoPorIsbn(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaPrestamo* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void PrestamoPorIsbn(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaPrestamo* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void PrestamoPorIsbn(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaPrestamo* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // Dado el titulo, retorna respuesta al prestamo y fecha de devolucion
      virtual void PrestamoPorTitulo(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo* request, ::biblioteca::RespuestaPrestamo* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PrestamoPorTitulo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaPrestamo* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void PrestamoPorTitulo(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo* request, ::biblioteca::RespuestaPrestamo* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void PrestamoPorTitulo(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo* request, ::biblioteca::RespuestaPrestamo* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void PrestamoPorTitulo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaPrestamo* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void PrestamoPorTitulo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaPrestamo* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // Dado el ISBN o codigo, retorna si se encuentra y cuantos disponibles hay
      virtual void Consulta(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaConsulta* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Consulta(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaConsulta* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Consulta(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaConsulta* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Consulta(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaConsulta* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Consulta(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaConsulta* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Consulta(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaConsulta* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // Dado el isbn, registra la devolucion
      virtual void Devolucion(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaDevolucion* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Devolucion(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaDevolucion* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Devolucion(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaDevolucion* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Devolucion(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaDevolucion* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Devolucion(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaDevolucion* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Devolucion(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaDevolucion* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaPrestamo>* AsyncPrestamoPorIsbnRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaPrestamo>* PrepareAsyncPrestamoPorIsbnRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaPrestamo>* AsyncPrestamoPorTituloRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaPrestamo>* PrepareAsyncPrestamoPorTituloRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaConsulta>* AsyncConsultaRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaConsulta>* PrepareAsyncConsultaRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaDevolucion>* AsyncDevolucionRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::biblioteca::RespuestaDevolucion>* PrepareAsyncDevolucionRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status PrestamoPorIsbn(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::biblioteca::RespuestaPrestamo* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaPrestamo>> AsyncPrestamoPorIsbn(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaPrestamo>>(AsyncPrestamoPorIsbnRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaPrestamo>> PrepareAsyncPrestamoPorIsbn(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaPrestamo>>(PrepareAsyncPrestamoPorIsbnRaw(context, request, cq));
    }
    ::grpc::Status PrestamoPorTitulo(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo& request, ::biblioteca::RespuestaPrestamo* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaPrestamo>> AsyncPrestamoPorTitulo(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaPrestamo>>(AsyncPrestamoPorTituloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaPrestamo>> PrepareAsyncPrestamoPorTitulo(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaPrestamo>>(PrepareAsyncPrestamoPorTituloRaw(context, request, cq));
    }
    ::grpc::Status Consulta(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::biblioteca::RespuestaConsulta* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaConsulta>> AsyncConsulta(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaConsulta>>(AsyncConsultaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaConsulta>> PrepareAsyncConsulta(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaConsulta>>(PrepareAsyncConsultaRaw(context, request, cq));
    }
    ::grpc::Status Devolucion(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::biblioteca::RespuestaDevolucion* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaDevolucion>> AsyncDevolucion(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaDevolucion>>(AsyncDevolucionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaDevolucion>> PrepareAsyncDevolucion(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaDevolucion>>(PrepareAsyncDevolucionRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void PrestamoPorIsbn(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaPrestamo* response, std::function<void(::grpc::Status)>) override;
      void PrestamoPorIsbn(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaPrestamo* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void PrestamoPorIsbn(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaPrestamo* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void PrestamoPorIsbn(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaPrestamo* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void PrestamoPorIsbn(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaPrestamo* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void PrestamoPorIsbn(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaPrestamo* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void PrestamoPorTitulo(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo* request, ::biblioteca::RespuestaPrestamo* response, std::function<void(::grpc::Status)>) override;
      void PrestamoPorTitulo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaPrestamo* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void PrestamoPorTitulo(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo* request, ::biblioteca::RespuestaPrestamo* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void PrestamoPorTitulo(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo* request, ::biblioteca::RespuestaPrestamo* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void PrestamoPorTitulo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaPrestamo* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void PrestamoPorTitulo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaPrestamo* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void Consulta(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaConsulta* response, std::function<void(::grpc::Status)>) override;
      void Consulta(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaConsulta* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Consulta(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaConsulta* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Consulta(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaConsulta* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Consulta(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaConsulta* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Consulta(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaConsulta* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void Devolucion(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaDevolucion* response, std::function<void(::grpc::Status)>) override;
      void Devolucion(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaDevolucion* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Devolucion(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaDevolucion* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Devolucion(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaDevolucion* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Devolucion(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaDevolucion* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Devolucion(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaDevolucion* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaPrestamo>* AsyncPrestamoPorIsbnRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaPrestamo>* PrepareAsyncPrestamoPorIsbnRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaPrestamo>* AsyncPrestamoPorTituloRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaPrestamo>* PrepareAsyncPrestamoPorTituloRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaConsulta>* AsyncConsultaRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaConsulta>* PrepareAsyncConsultaRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaDevolucion>* AsyncDevolucionRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaDevolucion>* PrepareAsyncDevolucionRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_PrestamoPorIsbn_;
    const ::grpc::internal::RpcMethod rpcmethod_PrestamoPorTitulo_;
    const ::grpc::internal::RpcMethod rpcmethod_Consulta_;
    const ::grpc::internal::RpcMethod rpcmethod_Devolucion_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Dado el isbn, retorna respuesta al prestamo y fecha de devolucion
    virtual ::grpc::Status PrestamoPorIsbn(::grpc::ServerContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaPrestamo* response);
    // Dado el titulo, retorna respuesta al prestamo y fecha de devolucion
    virtual ::grpc::Status PrestamoPorTitulo(::grpc::ServerContext* context, const ::biblioteca::PeticionTitulo* request, ::biblioteca::RespuestaPrestamo* response);
    // Dado el ISBN o codigo, retorna si se encuentra y cuantos disponibles hay
    virtual ::grpc::Status Consulta(::grpc::ServerContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaConsulta* response);
    // Dado el isbn, registra la devolucion
    virtual ::grpc::Status Devolucion(::grpc::ServerContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaDevolucion* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_PrestamoPorIsbn : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PrestamoPorIsbn() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PrestamoPorIsbn() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrestamoPorIsbn(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaPrestamo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPrestamoPorIsbn(::grpc::ServerContext* context, ::biblioteca::PeticionIsbn* request, ::grpc::ServerAsyncResponseWriter< ::biblioteca::RespuestaPrestamo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PrestamoPorTitulo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PrestamoPorTitulo() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_PrestamoPorTitulo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrestamoPorTitulo(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionTitulo* /*request*/, ::biblioteca::RespuestaPrestamo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPrestamoPorTitulo(::grpc::ServerContext* context, ::biblioteca::PeticionTitulo* request, ::grpc::ServerAsyncResponseWriter< ::biblioteca::RespuestaPrestamo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Consulta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Consulta() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_Consulta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Consulta(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaConsulta* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConsulta(::grpc::ServerContext* context, ::biblioteca::PeticionIsbn* request, ::grpc::ServerAsyncResponseWriter< ::biblioteca::RespuestaConsulta>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Devolucion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Devolucion() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_Devolucion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Devolucion(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaDevolucion* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDevolucion(::grpc::ServerContext* context, ::biblioteca::PeticionIsbn* request, ::grpc::ServerAsyncResponseWriter< ::biblioteca::RespuestaDevolucion>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_PrestamoPorIsbn<WithAsyncMethod_PrestamoPorTitulo<WithAsyncMethod_Consulta<WithAsyncMethod_Devolucion<Service > > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_PrestamoPorIsbn : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_PrestamoPorIsbn() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::biblioteca::PeticionIsbn, ::biblioteca::RespuestaPrestamo>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaPrestamo* response) { return this->PrestamoPorIsbn(context, request, response); }));}
    void SetMessageAllocatorFor_PrestamoPorIsbn(
        ::grpc::experimental::MessageAllocator< ::biblioteca::PeticionIsbn, ::biblioteca::RespuestaPrestamo>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::biblioteca::PeticionIsbn, ::biblioteca::RespuestaPrestamo>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_PrestamoPorIsbn() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrestamoPorIsbn(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaPrestamo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* PrestamoPorIsbn(
      ::grpc::CallbackServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaPrestamo* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* PrestamoPorIsbn(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaPrestamo* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_PrestamoPorTitulo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_PrestamoPorTitulo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::biblioteca::PeticionTitulo, ::biblioteca::RespuestaPrestamo>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::biblioteca::PeticionTitulo* request, ::biblioteca::RespuestaPrestamo* response) { return this->PrestamoPorTitulo(context, request, response); }));}
    void SetMessageAllocatorFor_PrestamoPorTitulo(
        ::grpc::experimental::MessageAllocator< ::biblioteca::PeticionTitulo, ::biblioteca::RespuestaPrestamo>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::biblioteca::PeticionTitulo, ::biblioteca::RespuestaPrestamo>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_PrestamoPorTitulo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrestamoPorTitulo(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionTitulo* /*request*/, ::biblioteca::RespuestaPrestamo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* PrestamoPorTitulo(
      ::grpc::CallbackServerContext* /*context*/, const ::biblioteca::PeticionTitulo* /*request*/, ::biblioteca::RespuestaPrestamo* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* PrestamoPorTitulo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::biblioteca::PeticionTitulo* /*request*/, ::biblioteca::RespuestaPrestamo* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Consulta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Consulta() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(2,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::biblioteca::PeticionIsbn, ::biblioteca::RespuestaConsulta>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaConsulta* response) { return this->Consulta(context, request, response); }));}
    void SetMessageAllocatorFor_Consulta(
        ::grpc::experimental::MessageAllocator< ::biblioteca::PeticionIsbn, ::biblioteca::RespuestaConsulta>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(2);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::biblioteca::PeticionIsbn, ::biblioteca::RespuestaConsulta>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Consulta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Consulta(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaConsulta* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Consulta(
      ::grpc::CallbackServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaConsulta* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Consulta(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaConsulta* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Devolucion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Devolucion() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(3,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::biblioteca::PeticionIsbn, ::biblioteca::RespuestaDevolucion>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaDevolucion* response) { return this->Devolucion(context, request, response); }));}
    void SetMessageAllocatorFor_Devolucion(
        ::grpc::experimental::MessageAllocator< ::biblioteca::PeticionIsbn, ::biblioteca::RespuestaDevolucion>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(3);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::biblioteca::PeticionIsbn, ::biblioteca::RespuestaDevolucion>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Devolucion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Devolucion(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaDevolucion* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Devolucion(
      ::grpc::CallbackServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaDevolucion* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Devolucion(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaDevolucion* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_PrestamoPorIsbn<ExperimentalWithCallbackMethod_PrestamoPorTitulo<ExperimentalWithCallbackMethod_Consulta<ExperimentalWithCallbackMethod_Devolucion<Service > > > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_PrestamoPorIsbn<ExperimentalWithCallbackMethod_PrestamoPorTitulo<ExperimentalWithCallbackMethod_Consulta<ExperimentalWithCallbackMethod_Devolucion<Service > > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_PrestamoPorIsbn : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PrestamoPorIsbn() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PrestamoPorIsbn() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrestamoPorIsbn(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaPrestamo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PrestamoPorTitulo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PrestamoPorTitulo() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_PrestamoPorTitulo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrestamoPorTitulo(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionTitulo* /*request*/, ::biblioteca::RespuestaPrestamo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Consulta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Consulta() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_Consulta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Consulta(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaConsulta* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Devolucion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Devolucion() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_Devolucion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Devolucion(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaDevolucion* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_PrestamoPorIsbn : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PrestamoPorIsbn() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_PrestamoPorIsbn() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrestamoPorIsbn(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaPrestamo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPrestamoPorIsbn(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PrestamoPorTitulo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PrestamoPorTitulo() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_PrestamoPorTitulo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrestamoPorTitulo(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionTitulo* /*request*/, ::biblioteca::RespuestaPrestamo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPrestamoPorTitulo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Consulta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Consulta() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_Consulta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Consulta(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaConsulta* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConsulta(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Devolucion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Devolucion() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_Devolucion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Devolucion(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaDevolucion* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDevolucion(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_PrestamoPorIsbn : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_PrestamoPorIsbn() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PrestamoPorIsbn(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_PrestamoPorIsbn() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrestamoPorIsbn(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaPrestamo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* PrestamoPorIsbn(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* PrestamoPorIsbn(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_PrestamoPorTitulo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_PrestamoPorTitulo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PrestamoPorTitulo(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_PrestamoPorTitulo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrestamoPorTitulo(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionTitulo* /*request*/, ::biblioteca::RespuestaPrestamo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* PrestamoPorTitulo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* PrestamoPorTitulo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Consulta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Consulta() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(2,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Consulta(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Consulta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Consulta(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaConsulta* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Consulta(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Consulta(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Devolucion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Devolucion() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(3,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Devolucion(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Devolucion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Devolucion(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaDevolucion* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Devolucion(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Devolucion(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PrestamoPorIsbn : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PrestamoPorIsbn() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::biblioteca::PeticionIsbn, ::biblioteca::RespuestaPrestamo>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::biblioteca::PeticionIsbn, ::biblioteca::RespuestaPrestamo>* streamer) {
                       return this->StreamedPrestamoPorIsbn(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PrestamoPorIsbn() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PrestamoPorIsbn(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaPrestamo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPrestamoPorIsbn(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::biblioteca::PeticionIsbn,::biblioteca::RespuestaPrestamo>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PrestamoPorTitulo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PrestamoPorTitulo() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::biblioteca::PeticionTitulo, ::biblioteca::RespuestaPrestamo>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::biblioteca::PeticionTitulo, ::biblioteca::RespuestaPrestamo>* streamer) {
                       return this->StreamedPrestamoPorTitulo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PrestamoPorTitulo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PrestamoPorTitulo(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionTitulo* /*request*/, ::biblioteca::RespuestaPrestamo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPrestamoPorTitulo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::biblioteca::PeticionTitulo,::biblioteca::RespuestaPrestamo>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Consulta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Consulta() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::biblioteca::PeticionIsbn, ::biblioteca::RespuestaConsulta>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::biblioteca::PeticionIsbn, ::biblioteca::RespuestaConsulta>* streamer) {
                       return this->StreamedConsulta(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Consulta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Consulta(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaConsulta* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedConsulta(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::biblioteca::PeticionIsbn,::biblioteca::RespuestaConsulta>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Devolucion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Devolucion() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::biblioteca::PeticionIsbn, ::biblioteca::RespuestaDevolucion>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::biblioteca::PeticionIsbn, ::biblioteca::RespuestaDevolucion>* streamer) {
                       return this->StreamedDevolucion(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Devolucion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Devolucion(::grpc::ServerContext* /*context*/, const ::biblioteca::PeticionIsbn* /*request*/, ::biblioteca::RespuestaDevolucion* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDevolucion(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::biblioteca::PeticionIsbn,::biblioteca::RespuestaDevolucion>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_PrestamoPorIsbn<WithStreamedUnaryMethod_PrestamoPorTitulo<WithStreamedUnaryMethod_Consulta<WithStreamedUnaryMethod_Devolucion<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_PrestamoPorIsbn<WithStreamedUnaryMethod_PrestamoPorTitulo<WithStreamedUnaryMethod_Consulta<WithStreamedUnaryMethod_Devolucion<Service > > > > StreamedService;
};

}  // namespace biblioteca


#endif  // GRPC_biblioteca_2eproto__INCLUDED
