// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: biblioteca.proto

#include "biblioteca.pb.h"
#include "biblioteca.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace biblioteca {

static const char* GestionBiblioteca_method_names[] = {
  "/biblioteca.GestionBiblioteca/PrestamoPorIsbn",
  "/biblioteca.GestionBiblioteca/PrestamoPorTitulo",
  "/biblioteca.GestionBiblioteca/Consulta",
  "/biblioteca.GestionBiblioteca/Devolucion",
};

std::unique_ptr< GestionBiblioteca::Stub> GestionBiblioteca::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GestionBiblioteca::Stub> stub(new GestionBiblioteca::Stub(channel));
  return stub;
}

GestionBiblioteca::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_PrestamoPorIsbn_(GestionBiblioteca_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PrestamoPorTitulo_(GestionBiblioteca_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Consulta_(GestionBiblioteca_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Devolucion_(GestionBiblioteca_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GestionBiblioteca::Stub::PrestamoPorIsbn(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::biblioteca::RespuestaPrestamo* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_PrestamoPorIsbn_, context, request, response);
}

void GestionBiblioteca::Stub::experimental_async::PrestamoPorIsbn(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaPrestamo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PrestamoPorIsbn_, context, request, response, std::move(f));
}

void GestionBiblioteca::Stub::experimental_async::PrestamoPorIsbn(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaPrestamo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PrestamoPorIsbn_, context, request, response, std::move(f));
}

void GestionBiblioteca::Stub::experimental_async::PrestamoPorIsbn(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaPrestamo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_PrestamoPorIsbn_, context, request, response, reactor);
}

void GestionBiblioteca::Stub::experimental_async::PrestamoPorIsbn(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaPrestamo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_PrestamoPorIsbn_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaPrestamo>* GestionBiblioteca::Stub::AsyncPrestamoPorIsbnRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::biblioteca::RespuestaPrestamo>::Create(channel_.get(), cq, rpcmethod_PrestamoPorIsbn_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaPrestamo>* GestionBiblioteca::Stub::PrepareAsyncPrestamoPorIsbnRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::biblioteca::RespuestaPrestamo>::Create(channel_.get(), cq, rpcmethod_PrestamoPorIsbn_, context, request, false);
}

::grpc::Status GestionBiblioteca::Stub::PrestamoPorTitulo(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo& request, ::biblioteca::RespuestaPrestamo* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_PrestamoPorTitulo_, context, request, response);
}

void GestionBiblioteca::Stub::experimental_async::PrestamoPorTitulo(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo* request, ::biblioteca::RespuestaPrestamo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PrestamoPorTitulo_, context, request, response, std::move(f));
}

void GestionBiblioteca::Stub::experimental_async::PrestamoPorTitulo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaPrestamo* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PrestamoPorTitulo_, context, request, response, std::move(f));
}

void GestionBiblioteca::Stub::experimental_async::PrestamoPorTitulo(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo* request, ::biblioteca::RespuestaPrestamo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_PrestamoPorTitulo_, context, request, response, reactor);
}

void GestionBiblioteca::Stub::experimental_async::PrestamoPorTitulo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaPrestamo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_PrestamoPorTitulo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaPrestamo>* GestionBiblioteca::Stub::AsyncPrestamoPorTituloRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::biblioteca::RespuestaPrestamo>::Create(channel_.get(), cq, rpcmethod_PrestamoPorTitulo_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaPrestamo>* GestionBiblioteca::Stub::PrepareAsyncPrestamoPorTituloRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionTitulo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::biblioteca::RespuestaPrestamo>::Create(channel_.get(), cq, rpcmethod_PrestamoPorTitulo_, context, request, false);
}

::grpc::Status GestionBiblioteca::Stub::Consulta(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::biblioteca::RespuestaConsulta* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Consulta_, context, request, response);
}

void GestionBiblioteca::Stub::experimental_async::Consulta(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaConsulta* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Consulta_, context, request, response, std::move(f));
}

void GestionBiblioteca::Stub::experimental_async::Consulta(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaConsulta* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Consulta_, context, request, response, std::move(f));
}

void GestionBiblioteca::Stub::experimental_async::Consulta(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaConsulta* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Consulta_, context, request, response, reactor);
}

void GestionBiblioteca::Stub::experimental_async::Consulta(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaConsulta* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Consulta_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaConsulta>* GestionBiblioteca::Stub::AsyncConsultaRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::biblioteca::RespuestaConsulta>::Create(channel_.get(), cq, rpcmethod_Consulta_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaConsulta>* GestionBiblioteca::Stub::PrepareAsyncConsultaRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::biblioteca::RespuestaConsulta>::Create(channel_.get(), cq, rpcmethod_Consulta_, context, request, false);
}

::grpc::Status GestionBiblioteca::Stub::Devolucion(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::biblioteca::RespuestaDevolucion* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Devolucion_, context, request, response);
}

void GestionBiblioteca::Stub::experimental_async::Devolucion(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaDevolucion* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Devolucion_, context, request, response, std::move(f));
}

void GestionBiblioteca::Stub::experimental_async::Devolucion(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaDevolucion* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Devolucion_, context, request, response, std::move(f));
}

void GestionBiblioteca::Stub::experimental_async::Devolucion(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaDevolucion* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Devolucion_, context, request, response, reactor);
}

void GestionBiblioteca::Stub::experimental_async::Devolucion(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblioteca::RespuestaDevolucion* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Devolucion_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaDevolucion>* GestionBiblioteca::Stub::AsyncDevolucionRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::biblioteca::RespuestaDevolucion>::Create(channel_.get(), cq, rpcmethod_Devolucion_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::biblioteca::RespuestaDevolucion>* GestionBiblioteca::Stub::PrepareAsyncDevolucionRaw(::grpc::ClientContext* context, const ::biblioteca::PeticionIsbn& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::biblioteca::RespuestaDevolucion>::Create(channel_.get(), cq, rpcmethod_Devolucion_, context, request, false);
}

GestionBiblioteca::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GestionBiblioteca_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GestionBiblioteca::Service, ::biblioteca::PeticionIsbn, ::biblioteca::RespuestaPrestamo>(
          [](GestionBiblioteca::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::biblioteca::PeticionIsbn* req,
             ::biblioteca::RespuestaPrestamo* resp) {
               return service->PrestamoPorIsbn(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GestionBiblioteca_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GestionBiblioteca::Service, ::biblioteca::PeticionTitulo, ::biblioteca::RespuestaPrestamo>(
          [](GestionBiblioteca::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::biblioteca::PeticionTitulo* req,
             ::biblioteca::RespuestaPrestamo* resp) {
               return service->PrestamoPorTitulo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GestionBiblioteca_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GestionBiblioteca::Service, ::biblioteca::PeticionIsbn, ::biblioteca::RespuestaConsulta>(
          [](GestionBiblioteca::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::biblioteca::PeticionIsbn* req,
             ::biblioteca::RespuestaConsulta* resp) {
               return service->Consulta(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GestionBiblioteca_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GestionBiblioteca::Service, ::biblioteca::PeticionIsbn, ::biblioteca::RespuestaDevolucion>(
          [](GestionBiblioteca::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::biblioteca::PeticionIsbn* req,
             ::biblioteca::RespuestaDevolucion* resp) {
               return service->Devolucion(ctx, req, resp);
             }, this)));
}

GestionBiblioteca::Service::~Service() {
}

::grpc::Status GestionBiblioteca::Service::PrestamoPorIsbn(::grpc::ServerContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaPrestamo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GestionBiblioteca::Service::PrestamoPorTitulo(::grpc::ServerContext* context, const ::biblioteca::PeticionTitulo* request, ::biblioteca::RespuestaPrestamo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GestionBiblioteca::Service::Consulta(::grpc::ServerContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaConsulta* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GestionBiblioteca::Service::Devolucion(::grpc::ServerContext* context, const ::biblioteca::PeticionIsbn* request, ::biblioteca::RespuestaDevolucion* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace biblioteca

